-- Arabic Settings for TRQ Design
-- Generated: 2026-01-18T11:07:32.064Z
-- Total Settings: 160

BEGIN TRANSACTION;

INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutHeroParagraph_ar', 'شركة متخصصة في تقديم حلول تصميمية مبتكرة وفعالة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutHeroTitle_ar', 'من نحن', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutImpactPara1_ar', 'لقد ساعدنا مئات العملاء على تحقيق أهدافهم من خلال حلول تصميمية مبتكرة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutImpactPara2_ar', 'نفخر بالعلاقات طويلة الأمد التي بنيناها مع عملائنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutImpactTitle_ar', 'تأثيرنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutMissionText_ar', 'تقديم خدمات تصميمية عالية الجودة تساعد العملاء على تحقيق أهدافهم وتجاوز توقعاتهم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutMissionTitle_ar', 'مهمتنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue1Desc_ar', 'نسعى دائماً للبحث عن حلول جديدة ومبتكرة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue1Title_ar', 'الابتكار', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue2Desc_ar', 'نلتزم بأعلى معايير الجودة في كل مشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue2Title_ar', 'الجودة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue3Desc_ar', 'نعمل بشكل وثيق مع عملائنا لفهم احتياجاتهم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue3Title_ar', 'التعاون', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue4Desc_ar', 'نهتم بالتأثير البيئي والاجتماعي لعملنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutValue4Title_ar', 'الاستدامة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutVisionText_ar', 'أن نكون الشركة الرائدة في تقديم حلول تصميمية مبتكرة تحول الأفكار إلى واقع ملموس', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutVisionTitle_ar', 'رؤيتنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhoWeArePara1_ar', 'TRQ Design هي شركة متخصصة في تقديم حلول تصميمية شاملة تجمع بين الإبداع والتكنولوجيا. نعمل مع العلامات التجارية الرائدة لإنشاء تجارب بصرية استثنائية.', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhoWeArePara2_ar', 'فريقنا يتكون من مصممين وخبراء تقنيين متخصصين في مختلف المجالات. نؤمن بأن التصميم الجيد ليس فقط جميل المظهر، بل يجب أن يكون فعالاً وقابلاً للاستخدام.', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhoWeArePara3_ar', 'منذ تأسيسنا، عملنا مع مئات العملاء من مختلف الصناعات، وحققنا نتائج استثنائية تتجاوز التوقعات.', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhoWeAreTitle_ar', 'من نحن', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhyChoose1_ar', 'خبرة تزيد عن 10 سنوات في مجال التصميم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhyChoose2_ar', 'فريق متخصص من المصممين والمطورين', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhyChoose3_ar', 'حلول مخصصة تناسب احتياجات عملائنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhyChoose4_ar', 'دعم مستمر وخدمة عملاء ممتازة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('aboutWhyChooseTitle_ar', 'لماذا تختار TRQ', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogArticleAuthor_ar', 'الكاتب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogArticleDate_ar', 'التاريخ', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogArticleReadMore_ar', 'اقرأ المزيد', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogArticleReadTime_ar', 'وقت القراءة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryAll_ar', 'الكل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryBusiness_ar', 'الأعمال', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryDesign_ar', 'التصميم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryDevelopment_ar', 'التطوير', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryTrends_ar', 'الاتجاهات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogCategoryTutorials_ar', 'الدروس', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogExploreDescription_ar', 'تصفح مجموعة واسعة من المقالات والموارد', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogExploreTitle_ar', 'استكشف المزيد', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogFeaturedLabel_ar', 'مقالة مميزة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogHeroParagraph_ar', 'اكتشف أحدث المقالات والنصائح في مجال التصميم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogHeroTitle_ar', 'المدونة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogNewsletterBtn_ar', 'اشترك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogNewsletterDescription_ar', 'احصل على أحدث المقالات والنصائح مباشرة في بريدك الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogNewsletterPlaceholder_ar', 'أدخل بريدك الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('blogNewsletterTitle_ar', 'اشترك في نشرتنا البريدية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonChatWhatsapp_ar', 'دردش معنا على واتس آب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonContactUs_ar', 'تواصل معنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonLoading_ar', 'جاري التحميل...', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonRequestPricing_ar', 'اطلب عرض سعر', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonSubmitRequest_ar', 'إرسال الطلب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('commonSubmitting_ar', 'جاري الإرسال...', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactFormEmail_ar', 'البريد الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactFormMessage_ar', 'الرسالة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactFormName_ar', 'الاسم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactFormPhone_ar', 'رقم الهاتف', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactFormSubject_ar', 'الموضوع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactHeroParagraph_ar', 'نحن هنا للإجابة على أسئلتك والاستماع إلى أفكارك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactHeroTitle_ar', 'تواصل معنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactInfoAddress_ar', 'العنوان', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactInfoEmail_ar', 'البريد الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactInfoPhone_ar', 'الهاتف', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('contactMapSection_ar', 'موقعنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeCtaDescription_ar', 'دعنا نساعدك في إنشاء حل تصميمي استثنائي يحقق أهدافك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeCtaPrimaryBtn_ar', 'ابدأ الآن', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeCtaSecondaryBtn_ar', 'تعرف على المزيد', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeCtaTitle_ar', 'هل أنت مستعد لتحويل رؤيتك؟', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeFeaturedDescription_ar', 'استكشف مجموعة من أفضل مشاريعنا التي تعكس التزامنا بالتميز والابتكار', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeFeaturedTitle_ar', 'المشاريع المميزة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeIntroText1_ar', 'نحن نؤمن بقوة التصميم الاستثنائي لتحويل الأفكار إلى واقع ملموس. مع خبرة تزيد عن 10 سنوات، نقدم حلولاً تصميمية مبتكرة تجمع بين الإبداع والوظيفية.', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeIntroText2_ar', 'فريقنا المتخصص يعمل بشغف لإنشاء تجارب بصرية استثنائية تترك انطباعاً دائماً لدى عملائنا.', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeIntroTitle_ar', 'إنشاء حلول تصميم خالدة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep1Desc_ar', 'نستمع إلى احتياجاتك ونفهم رؤيتك بعمق', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep1Title_ar', 'الاستشارة الأولية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep2Desc_ar', 'نطور استراتيجية تصميمية شاملة تتوافق مع أهدافك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep2Title_ar', 'التخطيط والتصميم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep3Desc_ar', 'نحول التصاميم إلى واقع باستخدام أحدث التقنيات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep3Title_ar', 'التطوير والتنفيذ', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep4Desc_ar', 'نختبر كل جزء بعناية لضمان الجودة العالية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep4Title_ar', 'الاختبار والتحسين', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep5Desc_ar', 'نطلق المشروع ونوفر الدعم المستمر', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('homeWorkflowStep5Title_ar', 'الإطلاق والدعم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioFilterAll_ar', 'الكل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioFilterApp_ar', 'تطبيقات الجوال', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioFilterBranding_ar', 'الهوية البصرية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioFilterPackaging_ar', 'تصميم العبوات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioFilterWeb_ar', 'تصميم المواقع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioHeroParagraph_ar', 'استكشف مجموعة من أفضل مشاريعنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioHeroTitle_ar', 'أعمالنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('portfolioViewProject_ar', 'عرض المشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingBudget_ar', 'الميزانية المتوقعة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingContactMethodEmail_ar', 'البريد الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingContactMethodPhone_ar', 'الهاتف', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingContactMethodWhatsapp_ar', 'واتس آب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingContactMethod_ar', 'طريقة التواصل المفضلة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingDescription_ar', 'وصف المشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingFormCompany_ar', 'اسم الشركة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingFormEmail_ar', 'البريد الإلكتروني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingFormIntro_ar', 'اطلب عرض سعر مخصص', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingFormName_ar', 'الاسم الكامل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingFormPhone_ar', 'رقم الهاتف', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingHeroParagraph_ar', 'نقدم عروضاً مرنة تناسب احتياجات وميزانيات مختلفة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingHeroTitle_ar', 'الأسعار والعروض', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingLocation_ar', 'الموقع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingProjectSize_ar', 'حجم المشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingProjectType_ar', 'نوع المشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingResponseTime_ar', 'سنرد عليك خلال 24 ساعة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingSubmitBtn_ar', 'إرسال الطلب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingSubmittingBtn_ar', 'جاري الإرسال...', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingTimeline_ar', 'الجدول الزمني', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingWhatToExpect1_ar', 'استقبال عرض سعر مفصل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingWhatToExpect2_ar', 'استشارة مجانية مع فريقنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingWhatToExpect3_ar', 'خطة عمل شاملة للمشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('pricingWhatToExpectTitle_ar', 'ماذا تتوقع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailAwardsTitle_ar', 'الجوائز', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailBackBtn_ar', 'العودة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailChallengeTitle_ar', 'التحدي', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailClientQuoteTitle_ar', 'رأي العميل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailClient_ar', 'العميل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailCtaBtn_ar', 'ابدأ مشروعك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailCtaDescription_ar', 'دعنا نساعدك في إنشاء مشروع مشابه', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailCtaTitle_ar', 'هل أعجبك هذا المشروع؟', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailDuration_ar', 'المدة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailFeaturesTitle_ar', 'المميزات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailGalleryTitle_ar', 'المعرض', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailLocation_ar', 'الموقع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailMaterialsTitle_ar', 'المواد المستخدمة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailOverviewTitle_ar', 'نظرة عامة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailSize_ar', 'الحجم', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailSolutionTitle_ar', 'الحل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailTeam_ar', 'الفريق', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('projectDetailYear_ar', 'السنة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesCtaBtn_ar', 'اطلب عرض سعر', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesCtaDescription_ar', 'تواصل معنا اليوم لمناقشة احتياجاتك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesCtaTitle_ar', 'هل تحتاج إلى خدمة تصميمية؟', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesHeroParagraph_ar', 'مجموعة شاملة من الخدمات التصميمية المتخصصة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesHeroTitle_ar', 'خدماتنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesHighlight1_ar', 'تصميم الهوية البصرية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesHighlight2_ar', 'تصميم الواجهات والتجارب', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesHighlight3_ar', 'تطوير المواقع والتطبيقات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesIntroText_ar', 'نقدم مجموعة واسعة من الخدمات التصميمية التي تغطي جميع احتياجات عملائنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('servicesIntroTitle_ar', 'ما الذي نقدمه', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowHeroParagraph_ar', 'نتبع عملية منظمة وفعالة لضمان نجاح كل مشروع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowHeroTitle_ar', 'عملية عملنا', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowIntroText_ar', 'نتبع منهجية محددة وفعالة في كل مشروع لضمان تحقيق أفضل النتائج', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowIntroTitle_ar', 'كيف نعمل', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep1Feature1_ar', 'فهم احتياجاتك وأهدافك', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep1Feature2_ar', 'تحليل السوق والمنافسين', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep1Title_ar', 'الاستشارة والاكتشاف', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep2Feature1_ar', 'وضع خطة تصميمية شاملة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep2Feature2_ar', 'تحديد الأهداف والمؤشرات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep2Title_ar', 'التخطيط والاستراتيجية', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep3Feature1_ar', 'إنشاء تصاميم مبتكرة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep3Feature2_ar', 'الحصول على ملاحظاتك وتحسينها', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep3Title_ar', 'التصميم والإبداع', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep4Feature1_ar', 'تطوير الحل بأحدث التقنيات', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep4Feature2_ar', 'اختبار شامل وضمان الجودة', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep4Title_ar', 'التطوير والتنفيذ', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep5Feature1_ar', 'إطلاق المشروع بنجاح', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep5Feature2_ar', 'توفير الدعم المستمر', datetime('now'));
INSERT OR REPLACE INTO settings (key, value, updatedAt) VALUES ('workflowStep5Title_ar', 'الإطلاق والدعم', datetime('now'));

COMMIT;

-- Verification
-- SELECT COUNT(*) as total_arabic_settings FROM settings WHERE key LIKE '%_ar';
